services:
  postgres:
    image: postgres:18.1-alpine
    container_name: runnerz_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: runnerz
    ports:
      - '5432:5432'
